[server]
headless = true
port = 8501
enableCORS = false
enableWebsocketCompression = false

[theme]
primaryColor = "#1ea47e"
backgroundColor = "#212750"
secondaryBackgroundColor = "#1a1a3d"
textColor = "#f8f8f2"

[global]
enableStaticServing = true
