# Usa una imagen base ligera de Python
FROM python:3.10-slim

# Crea un directorio de trabajo
WORKDIR /app

# Copia todo el código de la API al contenedor
COPY . .

# Expone el puerto 8000 (por defecto de FastAPI/Flask)
EXPOSE 8000


